'use strict';

// 戦争・クーデター・暴動・騒動などの出来事データ。少しずつ追加していく
// 想定のリストで、1件ずつ以下の形式で追加する。
//
//   {
//       start: 開始年 (この年になったら地図上に表示され始める),
//       end:   終了年 (この年になったら表示が消える。終了年自体は含まない。
//              regions.jsの各行の終了年と同じ規則),
//       x: 地図上のx座標, y: 地図上のy座標
//           (region_listのpos_x/pos_yと同じ単位・原点。国名一覧から
//           ジャンプした時と同じ座標系なので、近くの地域のpos_x/pos_yを
//           参考にするとよい),
//       type: 'war'(戦争) | 'coup'(クーデター) | 'riot'(暴動) |
//             'unrest'(騒動) のいずれか。地図上のアイコンが変わる
//             (省略時は'war'扱い),
//       name: { ja: '日本語名', en: '英語名', zh: '中国語名' }
//           (en/zhは省略可。省略時はjaがそのまま使われる。タップすると
//           この名前でWikipedia要約パネルが開く),
//       sides: { ja: '当事者(例: 日本 vs 連合国)', en: '...', zh: '...' }
//           (省略可。省略時は当事者の表示なし。ある程度ズームインすると
//           地図上に表示される),
//       disp_level: 0〜4の数値(省略可・既定値0)。この値未満のズーム
//           段階では地図上に表示されない(0なら常に表示。大きな戦争は
//           0のまま、地域限定の小さな出来事は2〜3にすると、ズームイン
//           した時だけ表示されるようになる)
//   }
//
// 例(実データを追加する際は下記のように書き足していく):
// { start: 1939, end: 1946, x: 2500, y: 600, type: 'war',
//   name: { ja: '第二次世界大戦', en: 'World War II', zh: '第二次世界大战' },
//   sides: { ja: '連合国 vs 枢軸国', en: 'Allies vs Axis', zh: '同盟国 vs 轴心国' } },

const war_list = [
	// 動作確認用のサンプル。実データを追加し始めたら削除してよい
	{ start: 1939, end: 1946, x: 1900, y: 375, type: 'war',
	  name: { ja: '第二次世界大戦', en: 'World War II', zh: '第二次世界大战' },
	  sides: { ja: '連合国 vs 枢軸国', en: 'Allies vs Axis', zh: '同盟国 vs 轴心国' } },

	// 赤壁の戦い(208年、長江中流域。魏の曹操軍 vs 孫権・劉備の連合軍)
	{ start: 208, end: 209, x: 2910, y: 590, type: 'war',
	  name: { ja: '赤壁の戦い', en: 'Battle of Red Cliffs', zh: '赤壁之战' },
	  sides: { ja: '曹操(魏) vs 孫権・劉備連合軍', en: 'Cao Cao vs Sun Quan–Liu Bei alliance', zh: '曹操 vs 孙权刘备联军' } },

	// 関ヶ原の戦い(1600年、美濃国関ヶ原。東軍(徳川家康) vs 西軍(石田三成))
	{ start: 1600, end: 1601, x: 3190, y: 565, type: 'war',
	  name: { ja: '関ヶ原の戦い', en: 'Battle of Sekigahara', zh: '关原之战' },
	  sides: { ja: '東軍(徳川家康) vs 西軍(石田三成)', en: 'Eastern Army (Tokugawa Ieyasu) vs Western Army (Ishida Mitsunari)', zh: '东军(德川家康) vs 西军(石田三成)' } },

	// ===== 古代(BC〜5世紀) =====
	{ start: -1194, end: -1183, x: 2075, y: 513, type: 'war',
	  name: { ja: 'トロイア戦争', en: 'Trojan War' },
	  sides: { ja: 'ギリシア連合軍 vs トロイア' } },
	{ start: -1150, end: -900, x: 2130, y: 585, type: 'war',
	  name: { ja: 'ペリシテ戦争', en: 'Philistine Wars' },
	  sides: { ja: '古代イスラエル(ヘブライ人) vs ペリシテ人' } },
	{ start: -743, end: -667, x: 2010, y: 535, type: 'war',
	  name: { ja: 'メッセニア戦争', en: 'Messenian Wars' },
	  sides: { ja: 'スパルタ vs メッセニア' } },
	{ start: -499, end: -448, x: 2015, y: 520, type: 'war',
	  name: { ja: 'ペルシア戦争', en: 'Greco-Persian Wars' },
	  sides: { ja: 'ギリシア都市国家連合 vs アケメネス朝ペルシア' } },
	{ start: -431, end: -403, x: 2018, y: 525, type: 'war',
	  name: { ja: 'ペロポネソス戦争', en: 'Peloponnesian War' },
	  sides: { ja: 'アテナイ(デロス同盟) vs スパルタ(ペロポネソス同盟)' } },
	{ start: -398, end: -366, x: 1940, y: 522, type: 'war',
	  name: { ja: 'ディオニュシオス戦争', en: 'Wars of Dionysius' },
	  sides: { ja: 'シラクサ(ディオニュシオス1世) vs カルタゴ' } },
	{ start: -395, end: -386, x: 2010, y: 525, type: 'war',
	  name: { ja: 'コリントス戦争', en: 'Corinthian War' },
	  sides: { ja: 'スパルタ vs アテナイ・テーベ・コリントス・アルゴス連合' } },
	{ start: -343, end: -289, x: 1920, y: 478, type: 'war',
	  name: { ja: 'サムニウム戦争', en: 'Samnite Wars' },
	  sides: { ja: 'ローマ共和国 vs サムニウム人' } },
	{ start: -334, end: -322, x: 2150, y: 530, type: 'war',
	  name: { ja: 'アレクサンドロス大王の遠征', en: "Alexander the Great's conquests" },
	  sides: { ja: 'マケドニア王国 vs アケメネス朝ペルシア' } },
	{ start: -323, end: -321, x: 2015, y: 520, type: 'war',
	  name: { ja: 'ギリシア戦争(ラミア戦争)', en: 'Lamian War' },
	  sides: { ja: 'アテナイ等ギリシア諸都市 vs マケドニア' } },
	{ start: -322, end: -274, x: 2020, y: 490, type: 'war',
	  name: { ja: 'ディアドコイ戦争', en: 'Wars of the Diadochi' },
	  sides: { ja: 'アレクサンドロス大王の後継者(ディアドコイ)同士の抗争' } },
	{ start: -264, end: -145, x: 1900, y: 530, type: 'war',
	  name: { ja: 'ポエニ戦争', en: 'Punic Wars' },
	  sides: { ja: 'ローマ共和国 vs カルタゴ' } },
	{ start: -229, end: -218, x: 1975, y: 480, type: 'war',
	  name: { ja: 'イリュリア戦争', en: 'Illyrian Wars' },
	  sides: { ja: 'ローマ共和国 vs イリュリア' } },
	{ start: -214, end: -147, x: 2020, y: 490, type: 'war',
	  name: { ja: 'マケドニア戦争', en: 'Macedonian Wars' },
	  sides: { ja: 'ローマ共和国 vs マケドニア王国' } },
	{ start: -206, end: -201, x: 2900, y: 555, type: 'war',
	  name: { ja: '楚漢戦争', en: 'Chu–Han Contention' },
	  sides: { ja: '項羽(楚) vs 劉邦(漢)' } },
	{ start: -167, end: -159, x: 2155, y: 575, type: 'war',
	  name: { ja: 'マカベア戦争', en: 'Maccabean Revolt' },
	  sides: { ja: 'ユダヤ人(マカバイ家) vs セレウコス朝' } },
	{ start: -155, end: -138, x: 1680, y: 530, type: 'war',
	  name: { ja: 'ルシタニア戦争', en: 'Lusitanian War' },
	  sides: { ja: 'ローマ共和国 vs ルシタニア人' } },
	{ start: -146, end: -145, x: 2015, y: 520, type: 'war',
	  name: { ja: 'アカイア戦争', en: 'Achaean War' },
	  sides: { ja: 'ローマ共和国 vs アカイア同盟' } },
	{ start: -135, end: -70, x: 1920, y: 500, type: 'war',
	  name: { ja: '奴隷戦争', en: 'Servile Wars' },
	  sides: { ja: 'ローマ共和国 vs 奴隷反乱軍(スパルタクスら)' } },
	{ start: -113, end: -100, x: 1850, y: 450, type: 'war',
	  name: { ja: 'キンブリ=テウトニ戦争', en: 'Cimbrian War' },
	  sides: { ja: 'ローマ共和国 vs キンブリ族・テウトニ族' } },
	{ start: -112, end: -105, x: 1800, y: 550, type: 'war',
	  name: { ja: 'ユグルタ戦争', en: 'Jugurthine War' },
	  sides: { ja: 'ローマ共和国 vs ヌミディア(ユグルタ)' } },
	{ start: -91, end: -87, x: 1920, y: 480, type: 'war',
	  name: { ja: '同盟市戦争', en: 'Social War' },
	  sides: { ja: 'ローマ共和国 vs イタリア同盟諸都市' } },
	{ start: -88, end: -62, x: 2160, y: 510, type: 'war',
	  name: { ja: 'ミトリダテス戦争', en: 'Mithridatic Wars' },
	  sides: { ja: 'ローマ共和国 vs ポントス王国(ミトリダテス6世)' } },
	{ start: -80, end: -71, x: 1680, y: 530, type: 'war',
	  name: { ja: 'セルトリウス戦争', en: 'Sertorian War' },
	  sides: { ja: 'ローマ共和国 vs セルトリウス派(ヒスパニア)' } },
	{ start: -58, end: -49, x: 1800, y: 424, type: 'war',
	  name: { ja: 'ガリア戦争', en: 'Gallic Wars' },
	  sides: { ja: 'ローマ共和国(カエサル) vs ガリア諸部族' } },
	{ start: 66, end: 74, x: 2155, y: 575, type: 'war',
	  name: { ja: 'ユダヤ戦争', en: 'First Jewish–Roman War' },
	  sides: { ja: 'ローマ帝国 vs ユダヤ人(ユダヤ属州反乱)' } },
	{ start: 101, end: 107, x: 2055, y: 433, type: 'war',
	  name: { ja: 'ダキア戦争', en: 'Dacian Wars' },
	  sides: { ja: 'ローマ帝国(トラヤヌス) vs ダキア王国(デケバルス)' } },

	// ===== 中世(5〜15世紀) =====
	{ start: 533, end: 535, x: 1880, y: 540, type: 'war',
	  name: { ja: 'ヴァンダル戦争', en: 'Vandalic War' },
	  sides: { ja: '東ローマ帝国 vs ヴァンダル王国' } },
	{ start: 535, end: 555, x: 1910, y: 480, type: 'war',
	  name: { ja: 'ゴート戦争', en: 'Gothic War' },
	  sides: { ja: '東ローマ帝国 vs 東ゴート王国' } },
	{ start: 726, end: 744, x: 2060, y: 490, type: 'war',
	  name: { ja: '聖像戦争', en: 'Byzantine Iconoclasm conflict' },
	  sides: { ja: '聖像破壊派(皇帝レオン3世ら) vs 聖像崇拝派' } },
	{ start: 772, end: 805, x: 1900, y: 390, type: 'war',
	  name: { ja: 'ザクセン戦争', en: 'Saxon Wars' },
	  sides: { ja: 'フランク王国(カール大帝) vs ザクセン人' } },
	{ start: 1096, end: 1292, x: 2155, y: 575, type: 'war',
	  name: { ja: '十字軍', en: 'Crusades' },
	  sides: { ja: '西欧十字軍 vs イスラム諸勢力' } },
	{ start: 1206, end: 1369, x: 2940, y: 360, type: 'war',
	  name: { ja: 'モンゴル征服戦争', en: 'Mongol conquests' },
	  sides: { ja: 'モンゴル帝国 vs ユーラシア各地の諸国' } },
	{ start: 1255, end: 1382, x: 1960, y: 470, type: 'war',
	  name: { ja: 'ヴェネツィア=ジェノヴァ戦争', en: 'Venetian–Genoese Wars' },
	  sides: { ja: 'ヴェネツィア共和国 vs ジェノヴァ共和国' } },
	{ start: 1260, end: 1265, x: 2940, y: 360, type: 'war',
	  name: { ja: 'モンゴル帝国帝位継承戦争', en: 'Toluid Civil War' },
	  sides: { ja: 'クビライ vs アリクブケ' } },
	{ start: 1337, end: 1454, x: 1800, y: 424, type: 'war',
	  name: { ja: '百年戦争', en: "Hundred Years' War" },
	  sides: { ja: 'イングランド王国 vs フランス王国' } },
	{ start: 1404, end: 1434, x: 1900, y: 470, type: 'war',
	  name: { ja: 'ヴェネツィア=ミラノ戦争', en: 'Venetian–Milanese Wars' },
	  sides: { ja: 'ヴェネツィア共和国 vs ミラノ公国' } },
	{ start: 1419, end: 1435, x: 1970, y: 400, type: 'war',
	  name: { ja: 'フス戦争', en: 'Hussite Wars' },
	  sides: { ja: 'フス派(ボヘミア) vs 神聖ローマ帝国(カトリック十字軍)' } },
	{ start: 1443, end: 1479, x: 2000, y: 480, type: 'war',
	  name: { ja: 'アルバニア=トルコ戦争', en: 'Albanian–Ottoman Wars' },
	  sides: { ja: 'アルバニア(スカンデルベグ) vs オスマン帝国' } },
	{ start: 1454, end: 1467, x: 2010, y: 360, type: 'war',
	  name: { ja: '十三年戦争', en: "Thirteen Years' War" },
	  sides: { ja: 'ポーランド王国 vs ドイツ騎士団' } },
	{ start: 1455, end: 1488, x: 1760, y: 345, type: 'war',
	  name: { ja: '薔薇戦争', en: 'Wars of the Roses' },
	  sides: { ja: 'ランカスター家 vs ヨーク家' } },
	{ start: 1474, end: 1486, x: 1870, y: 420, type: 'war',
	  name: { ja: 'ブルゴーニュ戦争', en: 'Burgundian Wars' },
	  sides: { ja: 'ブルゴーニュ公国(シャルル突進公) vs スイス同盟・ロレーヌ・フランス' } },
	{ start: 1494, end: 1560, x: 1910, y: 480, type: 'war',
	  name: { ja: 'イタリア戦争', en: 'Italian Wars' },
	  sides: { ja: 'フランス王国 vs 神聖ローマ帝国・スペイン' } },
	{ start: 1499, end: 1500, x: 1900, y: 410, type: 'war',
	  name: { ja: 'シュヴァーベン戦争', en: 'Swabian War' },
	  sides: { ja: 'スイス同盟 vs 神聖ローマ帝国(シュヴァーベン同盟)' } },

	// ===== 近世(16〜18世紀) =====
	{ start: 1522, end: 1524, x: 1900, y: 390, type: 'war',
	  name: { ja: '騎士戦争', en: "Knights' Revolt" },
	  sides: { ja: '帝国騎士(ジッキンゲン) vs 諸侯連合' } },
	{ start: 1524, end: 1526, x: 1900, y: 390, type: 'war',
	  name: { ja: 'ドイツ農民戦争', en: "German Peasants' War" },
	  sides: { ja: '農民反乱軍 vs 諸侯・貴族連合' } },
	{ start: 1546, end: 1548, x: 1900, y: 390, type: 'war',
	  name: { ja: 'シュマルカルデン戦争', en: 'Schmalkaldic War' },
	  sides: { ja: 'シュマルカルデン同盟(プロテスタント諸侯) vs 神聖ローマ皇帝カール5世' } },
	{ start: 1558, end: 1584, x: 2100, y: 340, type: 'war',
	  name: { ja: 'リヴォニア戦争', en: 'Livonian War' },
	  sides: { ja: 'ロシア・ツァーリ国 vs リヴォニア騎士団・ポーランド・スウェーデン・デンマーク' } },
	{ start: 1562, end: 1599, x: 1800, y: 424, type: 'war',
	  name: { ja: 'ユグノー戦争', en: 'French Wars of Religion' },
	  sides: { ja: 'カトリック(ギーズ家) vs プロテスタント(ユグノー)' } },
	{ start: 1568, end: 1649, x: 1850, y: 390, type: 'war',
	  name: { ja: '八十年戦争', en: "Eighty Years' War" },
	  sides: { ja: 'オランダ(ネーデルラント連邦) vs スペイン' } },
	{ start: 1585, end: 1605, x: 1780, y: 350, type: 'war',
	  name: { ja: '英西戦争', en: 'Anglo–Spanish War' },
	  sides: { ja: 'イングランド王国 vs スペイン' } },
	{ start: 1591, end: 1607, x: 2000, y: 460, type: 'war',
	  name: { ja: '十五年戦争', en: 'Long Turkish War' },
	  sides: { ja: '神聖ローマ帝国・ハンガリー vs オスマン帝国' } },
	{ start: 1610, end: 1618, x: 2150, y: 340, type: 'war',
	  name: { ja: 'イングリア戦争', en: 'Ingrian War' },
	  sides: { ja: 'スウェーデン vs ロシア・ツァーリ国' } },
	{ start: 1611, end: 1614, x: 1930, y: 310, type: 'war',
	  name: { ja: 'カルマル戦争', en: 'Kalmar War' },
	  sides: { ja: 'デンマーク=ノルウェー vs スウェーデン' } },
	{ start: 1618, end: 1649, x: 1900, y: 390, type: 'war',
	  name: { ja: '三十年戦争', en: "Thirty Years' War" },
	  sides: { ja: 'プロテスタント諸侯・同盟国 vs カトリック(神聖ローマ皇帝)陣営' } },
	{ start: 1636, end: 1658, x: 2550, y: 650, type: 'war',
	  name: { ja: 'アウラングゼーブ戦争', en: "Aurangzeb's wars" },
	  sides: { ja: 'ムガル帝国(アウラングゼーブ) vs デカン諸王国' } },
	{ start: 1652, end: 1785, x: 1800, y: 360, type: 'war',
	  name: { ja: '英蘭戦争', en: 'Anglo–Dutch Wars' },
	  sides: { ja: 'イングランド(イギリス) vs オランダ' } },
	{ start: 1655, end: 1661, x: 2000, y: 370, type: 'war',
	  name: { ja: '北方戦争', en: 'Second Northern War' },
	  sides: { ja: 'スウェーデン vs ポーランド・ロシア・デンマーク連合' } },
	{ start: 1667, end: 1669, x: 1830, y: 400, type: 'war',
	  name: { ja: '南ネーデルラント継承戦争', en: 'War of Devolution' },
	  sides: { ja: 'フランス(ルイ14世) vs スペイン' } },
	{ start: 1672, end: 1679, x: 1850, y: 390, type: 'war',
	  name: { ja: 'オランダ侵略戦争', en: 'Franco–Dutch War' },
	  sides: { ja: 'フランス vs オランダ・スペイン・神聖ローマ帝国連合' } },
	{ start: 1675, end: 1680, x: 1930, y: 320, type: 'war',
	  name: { ja: 'スコーネ戦争', en: 'Scanian War' },
	  sides: { ja: 'デンマーク vs スウェーデン' } },
	{ start: 1681, end: 1708, x: 2550, y: 660, type: 'war',
	  name: { ja: 'デカン戦争', en: 'Mughal–Maratha Wars (Deccan)' },
	  sides: { ja: 'ムガル帝国 vs マラーター同盟' } },
	{ start: 1688, end: 1698, x: 1870, y: 400, type: 'war',
	  name: { ja: 'ファルツ継承戦争(九年戦争)', en: "Nine Years' War" },
	  sides: { ja: 'フランス vs アウクスブルク同盟(神聖ローマ帝国・イギリス・オランダ・スペイン)' } },
	{ start: 1689, end: 1698, x: 950, y: 470, type: 'war',
	  name: { ja: 'ウィリアム王戦争', en: "King William's War" },
	  sides: { ja: 'イギリス領北米植民地 vs フランス領北米植民地' } },
	{ start: 1700, end: 1722, x: 2050, y: 330, type: 'war',
	  name: { ja: '大北方戦争', en: 'Great Northern War' },
	  sides: { ja: 'スウェーデン vs ロシア・デンマーク・ポーランド・サクソン連合' } },
	{ start: 1701, end: 1715, x: 1700, y: 530, type: 'war',
	  name: { ja: 'スペイン継承戦争', en: 'War of the Spanish Succession' },
	  sides: { ja: 'フランス・スペイン(ブルボン家) vs イギリス・オランダ・神聖ローマ帝国連合' } },
	{ start: 1702, end: 1714, x: 950, y: 470, type: 'war',
	  name: { ja: 'アン女王戦争', en: "Queen Anne's War" },
	  sides: { ja: 'イギリス領植民地 vs フランス・スペイン領植民地' } },
	{ start: 1704, end: 1758, x: 2950, y: 820, type: 'war',
	  name: { ja: 'ジャワ継承戦争', en: 'Javanese wars of succession' },
	  sides: { ja: 'マタラム王国諸派 vs オランダ東インド会社' } },
	{ start: 1733, end: 1739, x: 2000, y: 370, type: 'war',
	  name: { ja: 'ポーランド継承戦争', en: 'War of the Polish Succession' },
	  sides: { ja: 'フランス・スペイン・サルデーニャ vs オーストリア・ロシア' } },
	{ start: 1740, end: 1749, x: 1980, y: 420, type: 'war',
	  name: { ja: 'オーストリア継承戦争', en: 'War of the Austrian Succession' },
	  sides: { ja: 'プロイセン・フランス連合 vs オーストリア(マリア・テレジア)・イギリス連合' } },
	{ start: 1744, end: 1749, x: 950, y: 470, type: 'war',
	  name: { ja: 'ジョージ王戦争', en: "King George's War" },
	  sides: { ja: 'イギリス領植民地 vs フランス領植民地' } },
	{ start: 1746, end: 1764, x: 2600, y: 780, type: 'war',
	  name: { ja: 'カーナティック戦争', en: 'Carnatic Wars' },
	  sides: { ja: 'イギリス東インド会社 vs フランス東インド会社' } },
	{ start: 1754, end: 1764, x: 950, y: 470, type: 'war',
	  name: { ja: 'フレンチ=インディアン戦争', en: 'French and Indian War' },
	  sides: { ja: 'イギリス(植民地) vs フランス・先住民連合' } },
	{ start: 1756, end: 1764, x: 2000, y: 380, type: 'war',
	  name: { ja: '七年戦争', en: "Seven Years' War" },
	  sides: { ja: 'プロイセン・イギリス連合 vs オーストリア・フランス・ロシア連合' } },
	{ start: 1765, end: 1768, x: 2760, y: 700, type: 'war',
	  name: { ja: '泰緬戦争', en: 'Burmese–Siamese War' },
	  sides: { ja: 'コンバウン朝ビルマ vs アユタヤ王朝シャム' } },
	{ start: 1767, end: 1800, x: 2550, y: 770, type: 'war',
	  name: { ja: 'マイソール戦争', en: 'Anglo–Mysore Wars' },
	  sides: { ja: 'マイソール王国(ハイダル・アリー/ティプー・スルタン) vs イギリス東インド会社' } },
	{ start: 1774, end: 1775, x: 2590, y: 610, type: 'war',
	  name: { ja: 'ロヒラ戦争', en: 'Rohilla War' },
	  sides: { ja: 'アワド太守国・イギリス東インド会社 vs ローヒラ族' } },
	{ start: 1775, end: 1819, x: 2550, y: 650, type: 'war',
	  name: { ja: 'マラーター戦争', en: 'Anglo–Maratha Wars' },
	  sides: { ja: 'マラーター同盟 vs イギリス東インド会社' } },
	{ start: 1775, end: 1784, x: 950, y: 500, type: 'war',
	  name: { ja: 'アメリカ独立戦争', en: 'American Revolutionary War' },
	  sides: { ja: 'アメリカ13植民地(大陸軍) vs イギリス' } },
	{ start: 1779, end: 1880, x: 2010, y: 1220, type: 'war',
	  name: { ja: 'カフィル戦争', en: 'Cape Frontier Wars' },
	  sides: { ja: 'イギリス(ケープ植民地) vs コーサ人(カフィル)' } },
	{ start: 1792, end: 1803, x: 1900, y: 424, type: 'war',
	  name: { ja: 'フランス革命戦争', en: 'French Revolutionary Wars' },
	  sides: { ja: 'フランス共和国 vs 対仏大同盟(オーストリア・プロイセン・イギリスなど)' } },

	// ===== 近代(19世紀) =====
	{ start: 1800, end: 1806, x: 1940, y: 620, type: 'war',
	  name: { ja: 'トリポリ戦争', en: 'First Barbary War' },
	  sides: { ja: 'アメリカ合衆国 vs トリポリ(バーバリ海賊国家)' } },
	{ start: 1803, end: 1816, x: 1900, y: 420, type: 'war',
	  name: { ja: 'ナポレオン戦争', en: 'Napoleonic Wars' },
	  sides: { ja: 'フランス帝国(ナポレオン) vs 対仏大同盟諸国' } },
	{ start: 1812, end: 1816, x: 950, y: 470, type: 'war',
	  name: { ja: '米英戦争', en: 'War of 1812' },
	  sides: { ja: 'アメリカ合衆国 vs イギリス' } },
	{ start: 1814, end: 1817, x: 2650, y: 595, type: 'war',
	  name: { ja: 'グルカ戦争', en: 'Anglo–Nepalese War' },
	  sides: { ja: 'ネパール(グルカ王国) vs イギリス東インド会社' } },
	{ start: 1817, end: 1859, x: 1000, y: 560, type: 'war',
	  name: { ja: 'セミノール戦争', en: 'Seminole Wars' },
	  sides: { ja: 'アメリカ合衆国 vs セミノール族' } },
	{ start: 1821, end: 1838, x: 2870, y: 790, type: 'war',
	  name: { ja: 'パドリ戦争', en: 'Padri War' },
	  sides: { ja: 'パドリ派(イスラム改革派) vs アダット派・オランダ' } },
	{ start: 1821, end: 1831, x: 2015, y: 520, type: 'war',
	  name: { ja: 'ギリシア独立戦争', en: 'Greek War of Independence' },
	  sides: { ja: 'ギリシア独立派 vs オスマン帝国' } },
	{ start: 1824, end: 1886, x: 2745, y: 680, type: 'war',
	  name: { ja: 'ビルマ戦争', en: 'Anglo–Burmese Wars' },
	  sides: { ja: 'コンバウン朝ビルマ vs イギリス' } },
	{ start: 1824, end: 1833, x: 1760, y: 780, type: 'war',
	  name: { ja: 'アサンティ戦争', en: 'Anglo–Ashanti Wars' },
	  sides: { ja: 'アシャンティ王国 vs イギリス' } },
	{ start: 1825, end: 1831, x: 2950, y: 820, type: 'war',
	  name: { ja: 'ジャワ戦争', en: 'Java War' },
	  sides: { ja: 'ジャワ人(ディポヌゴロ) vs オランダ' } },
	{ start: 1825, end: 1829, x: 1250, y: 1180, type: 'war',
	  name: { ja: 'アルゼンチン=ブラジル戦争', en: 'Cisplatine War' },
	  sides: { ja: 'アルゼンチン(ラプラタ連合) vs ブラジル帝国' } },
	{ start: 1831, end: 1834, x: 2170, y: 600, type: 'war',
	  name: { ja: 'エジプト=トルコ戦争', en: 'Egyptian–Ottoman Wars' },
	  sides: { ja: 'エジプト(ムハンマド・アリー) vs オスマン帝国' } },
	{ start: 1831, end: 1833, x: 2870, y: 760, type: 'war',
	  name: { ja: 'ナニング戦争', en: 'Naning War' },
	  sides: { ja: 'イギリス(海峡植民地) vs ナニング' } },
	{ start: 1832, end: 1848, x: 1780, y: 560, type: 'war',
	  name: { ja: 'アブド=アルカーディル戦争', en: 'Algerian resistance of Abd el-Kader' },
	  sides: { ja: 'アブド・アルカーディル(アルジェリア) vs フランス' } },
	{ start: 1834, end: 1877, x: 1700, y: 530, type: 'war',
	  name: { ja: 'カルリスタ戦争', en: 'Carlist Wars' },
	  sides: { ja: 'カルリスタ派 vs 自由主義政府軍' } },
	{ start: 1839, end: 1920, x: 2430, y: 560, type: 'war',
	  name: { ja: 'アフガン戦争', en: 'Anglo–Afghan Wars' },
	  sides: { ja: 'アフガニスタン vs イギリス' } },
	{ start: 1839, end: 1843, x: 2980, y: 610, type: 'war',
	  name: { ja: 'アヘン戦争', en: 'Opium War' },
	  sides: { ja: '清 vs イギリス' } },
	{ start: 1845, end: 1850, x: 2560, y: 590, type: 'war',
	  name: { ja: 'シク戦争', en: 'Anglo–Sikh Wars' },
	  sides: { ja: 'シク王国(パンジャーブ) vs イギリス東インド会社' } },
	{ start: 1846, end: 1849, x: 830, y: 595, type: 'war',
	  name: { ja: '米墨戦争', en: 'Mexican–American War' },
	  sides: { ja: 'アメリカ合衆国 vs メキシコ' } },
	{ start: 1846, end: 1848, x: 2010, y: 1220, type: 'war',
	  name: { ja: '斧戦争', en: 'War of the Axe' },
	  sides: { ja: 'イギリス(ケープ植民地) vs コーサ人' } },
	{ start: 1847, end: 1848, x: 1900, y: 430, type: 'war',
	  name: { ja: 'ゾンダーブント戦争', en: 'Sonderbund War' },
	  sides: { ja: 'スイス・ゾンダーブント(カトリック諸州) vs スイス連邦(プロテスタント諸州)' } },
	{ start: 1848, end: 1871, x: 1910, y: 480, type: 'war',
	  name: { ja: 'イタリア統一戦争', en: 'Italian Wars of Independence' },
	  sides: { ja: 'サルデーニャ王国(イタリア統一派) vs オーストリア帝国' } },
	{ start: 1849, end: 1887, x: 750, y: 550, type: 'war',
	  name: { ja: 'アパッチ戦争', en: 'Apache Wars' },
	  sides: { ja: 'アメリカ合衆国 vs アパッチ族' } },
	{ start: 1853, end: 1857, x: 2140, y: 430, type: 'war',
	  name: { ja: 'クリミア戦争', en: 'Crimean War' },
	  sides: { ja: 'ロシア帝国 vs オスマン帝国・イギリス・フランス・サルデーニャ連合' } },
	{ start: 1856, end: 1861, x: 2980, y: 610, type: 'war',
	  name: { ja: 'アロー戦争', en: 'Second Opium War (Arrow War)' },
	  sides: { ja: '清 vs イギリス・フランス' } },
	{ start: 1857, end: 1862, x: 830, y: 610, type: 'war',
	  name: { ja: 'レフォルマ戦争', en: 'Reform War' },
	  sides: { ja: 'メキシコ自由主義派 vs 保守派' } },
	{ start: 1858, end: 1863, x: 2870, y: 750, type: 'war',
	  name: { ja: '仏越戦争', en: 'Cochinchina Campaign' },
	  sides: { ja: 'フランス vs ベトナム(阮朝)' } },
	{ start: 1860, end: 1866, x: 770, y: 540, type: 'war',
	  name: { ja: 'ナヴァホ戦争', en: 'Navajo Wars' },
	  sides: { ja: 'アメリカ合衆国 vs ナバホ族' } },
	{ start: 1861, end: 1866, x: 950, y: 540, type: 'war',
	  name: { ja: '南北戦争', en: 'American Civil War' },
	  sides: { ja: 'アメリカ合衆国(北部) vs アメリカ連合国(南部)' } },
	{ start: 1863, end: 1864, x: 3170, y: 590, type: 'war',
	  name: { ja: '薩英戦争', en: 'Anglo–Satsuma War' },
	  sides: { ja: '薩摩藩 vs イギリス' } },
	{ start: 1864, end: 1871, x: 1230, y: 1150, type: 'war',
	  name: { ja: 'パラグアイ戦争', en: 'Paraguayan War' },
	  sides: { ja: 'パラグアイ vs ブラジル・アルゼンチン・ウルグアイ三国同盟' } },
	{ start: 1864, end: 1865, x: 1890, y: 350, type: 'war',
	  name: { ja: 'デンマーク戦争', en: 'Second Schleswig War' },
	  sides: { ja: 'プロイセン・オーストリア vs デンマーク' } },
	{ start: 1866, end: 1867, x: 1970, y: 400, type: 'war',
	  name: { ja: '普墺戦争', en: 'Austro–Prussian War' },
	  sides: { ja: 'プロイセン vs オーストリア' } },
	{ start: 1868, end: 1870, x: 3190, y: 550, type: 'war',
	  name: { ja: '戊辰戦争', en: 'Boshin War' },
	  sides: { ja: '新政府軍(薩長) vs 旧幕府軍(奥羽越列藩同盟)' } },
	{ start: 1868, end: 1879, x: 1050, y: 650, type: 'war',
	  name: { ja: '十年戦争', en: "Ten Years' War" },
	  sides: { ja: 'キューバ独立派 vs スペイン' } },
	{ start: 1870, end: 1872, x: 1850, y: 410, type: 'war',
	  name: { ja: '普仏戦争', en: 'Franco–Prussian War' },
	  sides: { ja: 'プロイセン(北ドイツ連邦) vs フランス' } },
	{ start: 1873, end: 1905, x: 2830, y: 770, type: 'war',
	  name: { ja: 'アチェ戦争', en: 'Aceh War' },
	  sides: { ja: 'アチェ王国 vs オランダ' } },
	{ start: 1877, end: 1878, x: 3170, y: 590, type: 'war',
	  name: { ja: '西南戦争', en: 'Satsuma Rebellion' },
	  sides: { ja: '西郷隆盛(士族反乱軍) vs 明治政府軍' } },
	{ start: 1877, end: 1879, x: 2040, y: 460, type: 'war',
	  name: { ja: 'ロシア=トルコ戦争', en: 'Russo–Turkish War (1877–78)' },
	  sides: { ja: 'ロシア帝国 vs オスマン帝国' } },
	{ start: 1879, end: 1880, x: 2020, y: 1200, type: 'war',
	  name: { ja: 'ズールー戦争', en: 'Anglo–Zulu War' },
	  sides: { ja: 'イギリス vs ズールー王国' } },
	{ start: 1881, end: 1900, x: 2130, y: 650, type: 'war',
	  name: { ja: 'マフディー戦争', en: 'Mahdist War' },
	  sides: { ja: 'マフディー国家(スーダン) vs イギリス・エジプト' } },
	{ start: 1884, end: 1886, x: 2870, y: 730, type: 'war',
	  name: { ja: '清仏戦争', en: 'Sino–French War' },
	  sides: { ja: '清 vs フランス' } },
	{ start: 1885, end: 1886, x: 900, y: 700, type: 'war',
	  name: { ja: 'グアテマラ戦争', en: '1885 Central American War' },
	  sides: { ja: 'グアテマラ vs エルサルバドル等中米諸国' } },
	{ start: 1894, end: 1896, x: 3060, y: 540, type: 'war',
	  name: { ja: '日清戦争', en: 'First Sino–Japanese War' },
	  sides: { ja: '日本 vs 清' } },
	{ start: 1894, end: 1897, x: 2270, y: 700, type: 'war',
	  name: { ja: 'イタリア=エチオピア戦争', en: 'First Italo–Ethiopian War' },
	  sides: { ja: 'エチオピア帝国(メネリク2世) vs イタリア王国' } },
	{ start: 1897, end: 1898, x: 2020, y: 510, type: 'war',
	  name: { ja: '十三日戦争', en: "Thirty Days' War" },
	  sides: { ja: 'ギリシア王国 vs オスマン帝国' } },
	{ start: 1898, end: 1899, x: 1050, y: 650, type: 'war',
	  name: { ja: '米西戦争', en: 'Spanish–American War' },
	  sides: { ja: 'アメリカ合衆国 vs スペイン' } },
	{ start: 1899, end: 1903, x: 3050, y: 780, type: 'war',
	  name: { ja: '米比戦争', en: 'Philippine–American War' },
	  sides: { ja: 'アメリカ合衆国 vs フィリピン共和国' } },
	{ start: 1899, end: 1903, x: 1040, y: 855, type: 'war',
	  name: { ja: '千日戦争', en: "Thousand Days' War" },
	  sides: { ja: 'コロンビア自由党 vs 保守党' } },
	{ start: 1899, end: 1903, x: 2010, y: 1220, type: 'war',
	  name: { ja: '南アフリカ戦争', en: 'Second Boer War' },
	  sides: { ja: 'イギリス vs トランスヴァール共和国・オレンジ自由国(ボーア人)' } },

	// ===== 現代(20世紀以降) =====
	{ start: 1904, end: 1906, x: 2960, y: 530, type: 'war',
	  name: { ja: '日露戦争', en: 'Russo–Japanese War' },
	  sides: { ja: '日本 vs ロシア帝国' } },
	{ start: 1911, end: 1913, x: 1940, y: 620, type: 'war',
	  name: { ja: 'イタリア=トルコ戦争', en: 'Italo–Turkish War' },
	  sides: { ja: 'イタリア王国 vs オスマン帝国' } },
	{ start: 1912, end: 1914, x: 2020, y: 470, type: 'war',
	  name: { ja: 'バルカン戦争', en: 'Balkan Wars' },
	  sides: { ja: 'バルカン同盟(セルビア・ブルガリア・ギリシア・モンテネグロ) vs オスマン帝国' } },
	{ start: 1914, end: 1919, x: 1900, y: 400, type: 'war',
	  name: { ja: '第一次世界大戦', en: 'World War I' },
	  sides: { ja: '連合国(イギリス・フランス・ロシア等) vs 同盟国(ドイツ・オーストリア=ハンガリー等)' } },
	{ start: 1918, end: 1923, x: 2200, y: 350, type: 'war',
	  name: { ja: 'ロシア内戦', en: 'Russian Civil War' },
	  sides: { ja: '赤軍(ボリシェヴィキ) vs 白軍' } },
	{ start: 1918, end: 1926, x: 2400, y: 300, type: 'war',
	  name: { ja: '対ソ干渉戦争', en: 'Allied intervention in the Russian Civil War' },
	  sides: { ja: '連合国干渉軍 vs ソビエト赤軍' } },
	{ start: 1920, end: 1927, x: 1730, y: 575, type: 'war',
	  name: { ja: 'リーフ戦争', en: 'Rif War' },
	  sides: { ja: 'リーフ共和国 vs スペイン・フランス' } },
	{ start: 1920, end: 1921, x: 2900, y: 530, type: 'war',
	  name: { ja: '安直戦争', en: 'Zhili–Anhui War' },
	  sides: { ja: '直隷派 vs 安徽派' } },
	{ start: 1922, end: 1925, x: 2930, y: 520, type: 'war',
	  name: { ja: '奉直戦争', en: 'Zhili–Fengtian Wars' },
	  sides: { ja: '直隷派 vs 奉天派' } },
	{ start: 1932, end: 1936, x: 1200, y: 1120, type: 'war',
	  name: { ja: 'チャコ戦争', en: 'Chaco War' },
	  sides: { ja: 'パラグアイ vs ボリビア' } },
	{ start: 1936, end: 1940, x: 1700, y: 530, type: 'war',
	  name: { ja: 'スペイン内戦', en: 'Spanish Civil War' },
	  sides: { ja: '人民戦線政府軍 vs フランコ率いる反乱軍(国民派)' } },
	{ start: 1937, end: 1946, x: 2920, y: 560, type: 'war',
	  name: { ja: '日中戦争', en: 'Second Sino–Japanese War' },
	  sides: { ja: '日本 vs 中華民国' } },
	{ start: 1939, end: 1941, x: 2080, y: 320, type: 'war',
	  name: { ja: '冬戦争', en: 'Winter War' },
	  sides: { ja: 'ソビエト連邦 vs フィンランド' } },
	{ start: 1941, end: 1946, x: 3200, y: 600, type: 'war',
	  name: { ja: '太平洋戦争', en: 'Pacific War' },
	  sides: { ja: '日本 vs アメリカ合衆国等連合国' } },
	{ start: 1945, end: 1950, x: 2950, y: 820, type: 'war',
	  name: { ja: 'インドネシア独立戦争', en: 'Indonesian National Revolution' },
	  sides: { ja: 'インドネシア共和国 vs オランダ' } },
	{ start: 1946, end: 1955, x: 2860, y: 730, type: 'war',
	  name: { ja: 'インドシナ戦争', en: 'First Indochina War' },
	  sides: { ja: 'ベトナム民主共和国(ベトミン) vs フランス' } },
	{ start: 1947, end: 2020, x: 2560, y: 590, type: 'war',
	  name: { ja: '印パ戦争', en: 'Indo–Pakistani Wars' },
	  sides: { ja: 'インド vs パキスタン' } },
	{ start: 1948, end: 1974, x: 2150, y: 580, type: 'war',
	  name: { ja: '中東戦争', en: 'Arab–Israeli Wars' },
	  sides: { ja: 'イスラエル vs アラブ諸国連合' } },
	{ start: 1950, end: 1954, x: 3060, y: 520, type: 'war',
	  name: { ja: '朝鮮戦争', en: 'Korean War' },
	  sides: { ja: '大韓民国・国連軍 vs 朝鮮民主主義人民共和国・中国' } },
	{ start: 1954, end: 1963, x: 1840, y: 540, type: 'war',
	  name: { ja: 'アルジェリア戦争', en: 'Algerian War' },
	  sides: { ja: 'アルジェリア民族解放戦線(FLN) vs フランス' } },
	{ start: 1955, end: 2006, x: 2130, y: 650, type: 'war',
	  name: { ja: 'スーダン内戦', en: 'Sudanese Civil Wars' },
	  sides: { ja: 'スーダン政府(北部) vs 南部スーダン諸勢力' } },
	{ start: 1955, end: 1976, x: 2870, y: 750, type: 'war',
	  name: { ja: 'ベトナム戦争', en: 'Vietnam War' },
	  sides: { ja: '北ベトナム・南ベトナム解放民族戦線 vs 南ベトナム・アメリカ合衆国' } },
	{ start: 1958, end: 1977, x: 1650, y: 270, type: 'war',
	  name: { ja: 'タラ戦争', en: 'Cod Wars' },
	  sides: { ja: 'アイスランド vs イギリス' } },
	{ start: 1963, end: 1965, x: 1780, y: 560, type: 'war',
	  name: { ja: 'アルジェリア=モロッコ戦争', en: 'Sand War' },
	  sides: { ja: 'アルジェリア vs モロッコ' } },
	{ start: 1967, end: 1971, x: 1860, y: 842, type: 'war',
	  name: { ja: 'ビアフラ戦争', en: 'Nigerian Civil War' },
	  sides: { ja: 'ナイジェリア連邦政府 vs ビアフラ共和国' } },
	{ start: 1969, end: 1970, x: 930, y: 745, type: 'war',
	  name: { ja: 'サッカー戦争', en: 'Football War' },
	  sides: { ja: 'エルサルバドル vs ホンジュラス' } },
	{ start: 1975, end: 2020, x: 2160, y: 570, type: 'war',
	  name: { ja: 'レバノン内戦', en: 'Lebanese Civil War' },
	  sides: { ja: 'レバノン国内諸派(キリスト教徒・イスラム教徒等)' } },
	{ start: 1975, end: 2003, x: 1930, y: 930, type: 'war',
	  name: { ja: 'アンゴラ内戦', en: 'Angolan Civil War' },
	  sides: { ja: 'アンゴラ人民解放運動(MPLA) vs アンゴラ全面独立民族同盟(UNITA)' } },
	{ start: 1977, end: 1979, x: 2280, y: 780, type: 'war',
	  name: { ja: 'オガデン戦争', en: 'Ogaden War' },
	  sides: { ja: 'エチオピア vs ソマリア' } },
	{ start: 1979, end: 1980, x: 2870, y: 730, type: 'war',
	  name: { ja: '中越戦争', en: 'Sino–Vietnamese War' },
	  sides: { ja: '中国 vs ベトナム' } },
	{ start: 1980, end: 1989, x: 2270, y: 570, type: 'war',
	  name: { ja: 'イラン=イラク戦争', en: 'Iran–Iraq War' },
	  sides: { ja: 'イラク vs イラン' } },
	{ start: 1982, end: 1983, x: 1150, y: 1350, type: 'war',
	  name: { ja: 'フォークランド戦争', en: 'Falklands War' },
	  sides: { ja: 'イギリス vs アルゼンチン' } },
	{ start: 1983, end: 2010, x: 2650, y: 800, type: 'war',
	  name: { ja: 'スリランカ内戦', en: 'Sri Lankan Civil War' },
	  sides: { ja: 'スリランカ政府 vs タミル・イーラム解放のトラ(LTTE)' } },
	{ start: 1988, end: 2020, x: 2270, y: 850, type: 'war',
	  name: { ja: 'ソマリア内戦', en: 'Somali Civil War' },
	  sides: { ja: 'ソマリア国内諸勢力' } },
	{ start: 1990, end: 1995, x: 2050, y: 920, type: 'war',
	  name: { ja: 'ルワンダ内戦', en: 'Rwandan Civil War' },
	  sides: { ja: 'ルワンダ愛国戦線(RPF) vs ルワンダ政府軍・フツ過激派' } },
	{ start: 1990, end: 1992, x: 2260, y: 600, type: 'war',
	  name: { ja: '湾岸戦争', en: 'Gulf War' },
	  sides: { ja: '多国籍軍(アメリカ等) vs イラク' } },
	{ start: 1991, end: 2002, x: 2000, y: 460, type: 'war',
	  name: { ja: 'ユーゴスラビア内戦', en: 'Yugoslav Wars' },
	  sides: { ja: 'ユーゴスラビア各共和国(セルビア・クロアチア等)諸勢力' } },
	{ start: 1991, end: 2003, x: 1840, y: 540, type: 'war',
	  name: { ja: 'アルジェリア内戦', en: 'Algerian Civil War' },
	  sides: { ja: 'アルジェリア政府 vs イスラム救国戦線(FIS)系武装勢力' } },
	{ start: 1996, end: 2004, x: 1950, y: 920, type: 'war',
	  name: { ja: 'コンゴ戦争', en: 'Congo Wars' },
	  sides: { ja: 'コンゴ民主共和国政府 vs 反政府勢力・周辺国軍' } },
	{ start: 2001, end: 2020, x: 2430, y: 560, type: 'war',
	  name: { ja: 'アフガニスタン戦争', en: 'War in Afghanistan (2001–2021)' },
	  sides: { ja: 'アメリカ・NATO・アフガニスタン政府 vs ターリバーン' } },
	{ start: 2002, end: 2012, x: 1700, y: 790, type: 'war',
	  name: { ja: 'コートジボワール内戦', en: 'Ivorian Civil War' },
	  sides: { ja: 'コートジボワール政府軍 vs 反政府勢力(新勢力)' } },
	{ start: 2003, end: 2012, x: 2260, y: 590, type: 'war',
	  name: { ja: 'イラク戦争', en: 'Iraq War' },
	  sides: { ja: 'アメリカ・有志連合 vs イラク(フセイン政権)' } },
	{ start: 2008, end: 2020, x: 2145, y: 585, type: 'war',
	  name: { ja: 'ガザ戦争', en: 'Gaza War' },
	  sides: { ja: 'イスラエル vs ハマス' } },
	{ start: 2011, end: 2020, x: 1940, y: 620, type: 'war',
	  name: { ja: 'リビア内戦', en: 'Libyan Civil War' },
	  sides: { ja: 'カダフィ政権軍 vs 反体制派(国民評議会)' } },
	{ start: 2011, end: 2020, x: 2170, y: 540, type: 'war',
	  name: { ja: 'シリア内戦', en: 'Syrian Civil War' },
	  sides: { ja: 'シリア政府(アサド政権) vs 反体制派・IS等諸勢力' } },
	{ start: 2015, end: 2020, x: 2245, y: 740, type: 'war',
	  name: { ja: 'イエメン内戦', en: 'Yemeni Civil War' },
	  sides: { ja: 'イエメン政府(ハディ派) vs フーシ派' } },
];
